version: '3.3'

services:
  node:
    container_name: university_node
    # image: node:latest
    # environment:
    #   NODE_ENV: production
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9008:8080"
    volumes:
      - ./:/var/www/html
    working_dir:
      /var/www/html
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=university_app
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=database
    ports:
      - "8083:80"